using apiwise.Models.CProducto.Items;
using apiwise.Models.CProducto.Items.Categorizacion;
using AutoMapper;

namespace apiwise.Models.CProducto
{
    /// <summary>
    /// </summary>
    public class ProductosProfile : Profile
    {
        /// <summary>
        /// </summary>
        public ProductosProfile()
        {

            CreateMap<Producto, GetProductosResponseDto>()
                              .ForMember(dest => dest.id, opt => opt.MapFrom(o => o.CodigoProducto))
                              .ForMember(dest => dest.idVenta, opt => opt.MapFrom(o => o.CodigoVentaProducto))
                              .ForMember(dest => dest.idCompra, opt => opt.MapFrom(o => o.CodigoCompraProducto))
                              .ForMember(dest => dest.idBarra, opt => opt.MapFrom(o => o.CodigoBarraProducto))
                              .ForMember(dest => dest.idCatalogo, opt => opt.MapFrom(o => o.CodigoCatalogoProducto))
                              .ForMember(dest => dest.idmultiempresa, opt => opt.MapFrom(o => o.Idmultiempresas))
                              .ForMember(dest => dest.descripcion, opt => opt.MapFrom(o => o.DescripcionProducto))
                               .ForMember(dest => dest.descAd, opt => opt.MapFrom(o => o.DescripcionAdicionalProducto))
                               .ForMember(dest => dest.descCorta, opt => opt.MapFrom(o => o.DescripcionCortaProducto))
                               .ForMember(dest => dest.unidad, opt => opt.MapFrom(o => o.UnidadesProducto))
                               .ForMember(dest => dest.linea, opt => opt.MapFrom(o => o.LineasProducto))
                               .ForMember(dest => dest.categoria, opt => opt.MapFrom(o => o.CategoriasProducto))
                               .ForMember(dest => dest.grupo, opt => opt.MapFrom(o => o.GruposProducto))
                               .ForMember(dest => dest.marca, opt => opt.MapFrom(o => o.MarcasProducto))
                               .ForMember(dest => dest.color, opt => opt.MapFrom(o => o.ColoresProducto))
                               .ForMember(dest => dest.fecha, opt => opt.MapFrom(o => o.FechaCreacionProducto))
                               .ForMember(dest => dest.cuentasCompra, opt => opt.MapFrom(o => o.CuentasContabilidadCompraProducto))
                               .ForMember(dest => dest.cuentasVenta, opt => opt.MapFrom(o => o.CuentasContabilidadVentaProducto))
                               .ForMember(dest => dest.cuentasCosto, opt => opt.MapFrom(o => o.CuentasContabilidadCostoProducto))
                               .ForMember(dest => dest.cuentasDevolu, opt => opt.MapFrom(o => o.CuentasContabilidadDevolucionProducto))
                               .ForMember(dest => dest.CuentasContabilidadCuponProducto, opt => opt.MapFrom(o => o.CuentasContabilidadCuponProducto))
                               .ForMember(dest => dest.CuentasContabilidadDescuentoProducto, opt => opt.MapFrom(o => o.CuentasContabilidadDescuentoProducto))
                               .ForMember(dest => dest.cuentasActivo, opt => opt.MapFrom(o => o.CuentasContabilidadActivoProducto))
                               .ForMember(dest => dest.arancel, opt => opt.MapFrom(o => o.ArancelesProducto))
                               .ForMember(dest => dest.servicio, opt => opt.MapFrom(o => o.ServicioProducto))
                               .ForMember(dest => dest.pagaIva, opt => opt.MapFrom(o => o.PagaIvaProducto))
                               .ForMember(dest => dest.pagaIce, opt => opt.MapFrom(o => o.PagaIceProducto))
                               .ForMember(dest => dest.receta, opt => opt.MapFrom(o => o.RecetaProducto))
                               .ForMember(dest => dest.venta, opt => opt.MapFrom(o => o.VentaProducto))
                               .ForMember(dest => dest.activo, opt => opt.MapFrom(o => o.ActivoProducto))
                               .ForMember(dest => dest.serie, opt => opt.MapFrom(o => o.SerieLoteProducto))
                               .ForMember(dest => dest.lote, opt => opt.MapFrom(o => o.LoteProducto))
                               .ForMember(dest => dest.unidadCaja, opt => opt.MapFrom(o => o.UnidadesCajaProducto))
                               .ForMember(dest => dest.peso, opt => opt.MapFrom(o => o.PesoProducto))
                               .ForMember(dest => dest.alto, opt => opt.MapFrom(o => o.AltoProducto))
                               .ForMember(dest => dest.ancho, opt => opt.MapFrom(o => o.AnchoProducto))
                               .ForMember(dest => dest.profondidad, opt => opt.MapFrom(o => o.ProfundidadProducto))
                               .ForMember(dest => dest.precioFof, opt => opt.MapFrom(o => o.PrecioFofproducto))
                               .ForMember(dest => dest.materiaPrima, opt => opt.MapFrom(o => o.MateriaPrimaProducto))
                               .ForMember(dest => dest.ctrlPeso, opt => opt.MapFrom(o => o.ControlarPesoProducto))
                               .ForMember(dest => dest.repuesto, opt => opt.MapFrom(o => o.RepuestoProducto))
                               .ForMember(dest => dest.sustituto, opt => opt.MapFrom(o => o.SustitutoProducto))
                               .ForMember(dest => dest.accesorio, opt => opt.MapFrom(o => o.AccesorioProducto))
                               .ForMember(dest => dest.favorito, opt => opt.MapFrom(o => o.FavoritoProducto))
                               .ForMember(dest => dest.promo, opt => opt.MapFrom(o => o.PromocionProducto))
                               .ForMember(dest => dest.percha, opt => opt.MapFrom(o => o.PerchaProducto))
                               .ForMember(dest => dest.cultivo, opt => opt.MapFrom(o => o.CultivoProucto))
                               .ForMember(dest => dest.ctrl, opt => opt.MapFrom(o => o.ControlesProducto))
                               .ForMember(dest => dest.dosis, opt => opt.MapFrom(o => o.DosisProducto))
                               .ForMember(dest => dest.frecuencia, opt => opt.MapFrom(o => o.FrecuenciasProducto))
                               .ForMember(dest => dest.combo, opt => opt.MapFrom(o => o.ComboProducto))
                               .ForMember(dest => dest.descuentoCom, opt => opt.MapFrom(o => o.DescuentoComboProducto))
                               .ForMember(dest => dest.facturaCombo, opt => opt.MapFrom(o => o.FacturaComboProducto))
                               .ForMember(dest => dest.lista, opt => opt.MapFrom(o => o.ListasPrecioProducto))
                               .ForMember(dest => dest.facDecimal, opt => opt.MapFrom(o => o.FacturarDecimalesProducto))
                               .ForMember(dest => dest.selecc, opt => opt.MapFrom(o => o.SeleccionarPorcionesProducto))
                               .ForMember(dest => dest.observa, opt => opt.MapFrom(o => o.ObservacionProducto))
                               .ForMember(dest => dest.general, opt => opt.MapFrom(o => o.DatosGeneralesProducto))
                               .ForMember(dest => dest.ventaja, opt => opt.MapFrom(o => o.VentajasProducto))
                               .ForMember(dest => dest.desventaja, opt => opt.MapFrom(o => o.DesventajasProducto))
                               .ForMember(dest => dest.adicional, opt => opt.MapFrom(o => o.DatoAdicionalProducto))
                               .ForMember(dest => dest.tipos, opt => opt.MapFrom(o => o.ProductosTipoProducto))
                               .ForMember(dest => dest.proveedor, opt => opt.MapFrom(o => o.ProveedoresProducto))
                               .ForMember(dest => dest.precioProvee, opt => opt.MapFrom(o => o.PrecioProveedorLocalProducto))
                               .ForMember(dest => dest.variacion, opt => opt.MapFrom(o => o.VariacionCostoProduccionProducto))
                               .ForMember(dest => dest.metraje, opt => opt.MapFrom(o => o.MetrajeProducto))
                               .ForMember(dest => dest.porBoni, opt => opt.MapFrom(o => o.PorcentajeBonificacionProducto))
                               .ForMember(dest => dest.porDescuento, opt => opt.MapFrom(o => o.PorcentajeDescuentoProducto))
                               .ForMember(dest => dest.cantSumar, opt => opt.MapFrom(o => o.CantidadSumaBonificacionProducto))
                               .ForMember(dest => dest.filasSum, opt => opt.MapFrom(o => o.SumarNumeroFilasBonificacionProducto))
                               .ForMember(dest => dest.recargo, opt => opt.MapFrom(o => o.RecargoProducto))
                               .ForMember(dest => dest.califi, opt => opt.MapFrom(o => o.CalificacionProducto))
                               .ForMember(dest => dest.ctrlFuffer, opt => opt.MapFrom(o => o.ControlarBufferProducto))
                               .ForMember(dest => dest.tipoIce, opt => opt.MapFrom(o => o.CodigoTipoPorcentajeIce))
                               .ForMember(dest => dest.plan, opt => opt.MapFrom(o => o.PlanAnchoBanda))
                               .ForMember(dest => dest.CompresionServicio, opt => opt.MapFrom(o => o.CompresionServicio))
                               .ForMember(dest => dest.veriPlazo, opt => opt.MapFrom(o => o.VerificarPlazoLineasProducto))
                               .ForMember(dest => dest.motorChasis, opt => opt.MapFrom(o => o.IngresaMotorChasisProducto))
                               .ForMember(dest => dest.catServicio, opt => opt.MapFrom(o => o.CategoriasServicioTecnicoProducto))
                               .ForMember(dest => dest.tiempoServicio, opt => opt.MapFrom(o => o.TiempomedioServicioTecnicoProducto))
                               .ForMember(dest => dest.cantLitro, opt => opt.MapFrom(o => o.CantidadLitrosProducto))
                               .ForMember(dest => dest.gradoAlcohol, opt => opt.MapFrom(o => o.GradoAlcoholicoProducto))
                               .ForMember(dest => dest.valorPorLitro, opt => opt.MapFrom(o => o.ValorXlitroAlcoholProducto))
                               .ForMember(dest => dest.valorIce, opt => opt.MapFrom(o => o.ValorIcexItemProducto))
                               .ForMember(dest => dest.especial, opt => opt.MapFrom(o => o.CategoriasEspecialesProducto))
                               .ForMember(dest => dest.generaOrden, opt => opt.MapFrom(o => o.GeneraOrdenServicioTecnicoProducto))
                               .ForMember(dest => dest.sincroApp, opt => opt.MapFrom(o => o.SincronizarAppProducto))
                               .ForMember(dest => dest.sincroWeb, opt => opt.MapFrom(o => o.SincronizarWebProducto))
                               .ForMember(dest => dest.tipoExtra, opt => opt.MapFrom(o => o.TipoExtrasProducto))
                               .ForMember(dest => dest.descuento, opt => opt.MapFrom(o => o.DescuentoProducto))
                               .ForMember(dest => dest.visuaDesc, opt => opt.MapFrom(o => o.VisualizarDescuentoProducto))
                               .ForMember(dest => dest.esRecargas, opt => opt.MapFrom(o => o.EsServicioRecargasProducto))
                               .ForMember(dest => dest.EcommerceIdProducto, opt => opt.MapFrom(o => o.EcommerceIdProducto))
                               .ForMember(dest => dest.LineasEcommerceProducto, opt => opt.MapFrom(o => o.LineasEcommerceProducto))
                               .ForMember(dest => dest.CategoriasEcommerceProducto, opt => opt.MapFrom(o => o.CategoriasEcommerceProducto))
                               .ForMember(dest => dest.GruposEcommerceProducto, opt => opt.MapFrom(o => o.GruposEcommerceProducto))
                               .ForMember(dest => dest.MigarEcommerceProducto, opt => opt.MapFrom(o => o.MigarEcommerceProducto))
                               .ForMember(dest => dest.GruposCaracteristicasProducto, opt => opt.MapFrom(o => o.GruposCaracteristicasProducto))
                               .ForMember(dest => dest.DeshabilitadoProducto, opt => opt.MapFrom(o => o.DeshabilitadoProducto))
                               .ForMember(dest => dest.DeclaraArcsaProducto, opt => opt.MapFrom(o => o.DeclaraArcsaProducto))
                               .ForMember(dest => dest.NumeroRegistroSanitarioProducto, opt => opt.MapFrom(o => o.NumeroRegistroSanitarioProducto))
                               .ForMember(dest => dest.NombreComercialProducto, opt => opt.MapFrom(o => o.NombreComercialProducto))
                               .ForMember(dest => dest.CondicionesAlmacenamientoArcsaProducto, opt => opt.MapFrom(o => o.CondicionesAlmacenamientoArcsaProducto))
                               .ForMember(dest => dest.FechaVigenciaRegistroSanitarioProducto, opt => opt.MapFrom(o => o.FechaVigenciaRegistroSanitarioProducto))
                               .ForMember(dest => dest.Anio, opt => opt.MapFrom(o => o.Anio))
                               .ForMember(dest => dest.Tonelaje, opt => opt.MapFrom(o => o.Tonelaje))
                               .ForMember(dest => dest.PaisOrigen, opt => opt.MapFrom(o => o.PaisOrigen))
                               .ForMember(dest => dest.Combustible, opt => opt.MapFrom(o => o.Combustible))
                               .ForMember(dest => dest.Cilindraje, opt => opt.MapFrom(o => o.Cilindraje))
                               .ForMember(dest => dest.Capacidad, opt => opt.MapFrom(o => o.Capacidad))
                               .ForMember(dest => dest.NumeroEjes, opt => opt.MapFrom(o => o.NumeroEjes))
                               .ForMember(dest => dest.NumeroRuedas, opt => opt.MapFrom(o => o.NumeroRuedas))
                               .ForMember(dest => dest.usuario, opt => opt.MapFrom(o => o.UsuariosProducto));

            CreateMap<Producto, ResponseItemFranquicias>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(o => o.Idmultiempresas));

            CreateMap<Empresasproducto, EmpresasItemsDto>()
                .ForMember(dest => dest.idEmpresa, opt => opt.MapFrom(o => o.EmpresasEmpresaProducto))
                .ForMember(dest => dest.idItem, opt => opt.MapFrom(o => o.ProductosEmpresaProducto))
                .ForMember(dest => dest.costo, opt => opt.MapFrom(o => o.CostoProducto))
                .ForMember(dest => dest.pvp, opt => opt.MapFrom(o => o.PrecioVentaProducto))
                .ForMember(dest => dest.buffer, opt => opt.MapFrom(o => o.BufferEmpresaProducto))
                .ForMember(dest => dest.tipoem, opt => opt.MapFrom(o => o.TiposEstadoProductoEmpresaProducto))
                .ForMember(dest => dest.costoIn, opt => opt.MapFrom(o => o.CostoInicialProducto))
                .ForMember(dest => dest.descEmpPro, opt => opt.MapFrom(o => o.DescuentoProductoEmpresaProducto))
                .ForMember(dest => dest.visEmpPro, opt => opt.MapFrom(o => o.VisualizarDescuentoProductoEmpresaProducto))
                .ForMember(dest => dest.pMarcadoEmpPro, opt => opt.MapFrom(o => o.PrecioMarcadoEmpresaProducto))
                .ForMember(dest => dest.mUtilidadEmpPro, opt => opt.MapFrom(o => o.MargenUtilidadEmpresaProducto))
                .ForMember(dest => dest.compraminimamayoristaempresaproducto, opt => opt.MapFrom(o => o.Compraminimamayoristaempresaproducto))
                .ForMember(dest => dest.PorcentajeDescuentoMayoristaempresaproducto, opt => opt.MapFrom(o => o.PorcentajeDescuentoMayoristaempresaproducto))
                .ForMember(dest => dest.FacturaBajoCostoEmpresaProducto, opt => opt.MapFrom(o => o.FacturaBajoCostoEmpresaProducto))
                .ForMember(dest => dest.TieneRecetaXadis, opt => opt.MapFrom(o => o.TieneRecetaXadis))
                .ForMember(dest => dest.PorcentajeIncremento, opt => opt.MapFrom(o => o.PorcentajeIncrementoEmpresaProducto))
                .ForMember(dest => dest.ValorIce, opt => opt.MapFrom(o => o.ValorIce));

            CreateMap<Linea, LineaDto>()
                .ForMember(dest => dest.idLinea, opt => opt.MapFrom(o => o.CodigoLinea))
                .ForMember(dest => dest.nombre, opt => opt.MapFrom(o => o.NombreLinea))
                .ForMember(dest => dest.abreviado, opt => opt.MapFrom(o => o.AbreviadoLinea))
                .ForMember(dest => dest.presu, opt => opt.MapFrom(o => o.PresupuestoLinea))
                .ForMember(dest => dest.activa, opt => opt.MapFrom(o => o.ActivaLinea))
                .ForMember(dest => dest.venta, opt => opt.MapFrom(o => o.VentaLinea))
                .ForMember(dest => dest.usuLinea, opt => opt.MapFrom(o => o.UsuariosLinea));
            CreateMap<Categoria, CategoriaDto>()
                .ForMember(dest => dest.idCat, opt => opt.MapFrom(o => o.CodigoCategoria))
                .ForMember(dest => dest.nombreCat, opt => opt.MapFrom(o => o.NombreCategoria))
                .ForMember(dest => dest.abreCat, opt => opt.MapFrom(o => o.AbreviadoCategoria))
                .ForMember(dest => dest.lineasCat, opt => opt.MapFrom(o => o.LineasCategorias))
                .ForMember(dest => dest.activaCat, opt => opt.MapFrom(o => o.ActivaCategoria))
                .ForMember(dest => dest.presCat, opt => opt.MapFrom(o => o.PresupuestoCategoria))
                .ForMember(dest => dest.usuCat, opt => opt.MapFrom(o => o.UsuariosCategoria));

            CreateMap<Grupo, GrupoDto>()
                .ForMember(dest => dest.idGrupo, opt => opt.MapFrom(o => o.CodigoGrupo))
                .ForMember(dest => dest.nombreGru, opt => opt.MapFrom(o => o.NombreGrupo))
                .ForMember(dest => dest.abreGru, opt => opt.MapFrom(o => o.AbreviadoGrupo))
                .ForMember(dest => dest.cateGrupo, opt => opt.MapFrom(o => o.CategoriasGrupos))
                 .ForMember(dest => dest.idMarca, opt => opt.MapFrom(o => o.IdMarca))
                .ForMember(dest => dest.activaGru, opt => opt.MapFrom(o => o.ActivoGrupo))
                .ForMember(dest => dest.presGru, opt => opt.MapFrom(o => o.PresupuestoGrupo))
                .ForMember(dest => dest.usuGrup, opt => opt.MapFrom(o => o.UsuariosGrupo));

            CreateMap<Grupo, GrupoDto>()
                .ForMember(dest => dest.idGrupo, opt => opt.MapFrom(o => o.CodigoGrupo))
                .ForMember(dest => dest.nombreGru, opt => opt.MapFrom(o => o.NombreGrupo))
                .ForMember(dest => dest.abreGru, opt => opt.MapFrom(o => o.AbreviadoGrupo))
                .ForMember(dest => dest.cateGrupo, opt => opt.MapFrom(o => o.CategoriasGrupos))
                 .ForMember(dest => dest.idMarca, opt => opt.MapFrom(o => o.IdMarca))
                .ForMember(dest => dest.activaGru, opt => opt.MapFrom(o => o.ActivoGrupo))
                .ForMember(dest => dest.presGru, opt => opt.MapFrom(o => o.PresupuestoGrupo))
                .ForMember(dest => dest.usuGrup, opt => opt.MapFrom(o => o.UsuariosGrupo));

            CreateMap<Marca, MarcaDto>()
                .ForMember(dest => dest.idMarca, opt => opt.MapFrom(o => o.CodigoMarca))
                .ForMember(dest => dest.nombreMar, opt => opt.MapFrom(o => o.NombreMarca))
                .ForMember(dest => dest.abreMar, opt => opt.MapFrom(o => o.AbreviadoMarca))
                .ForMember(dest => dest.presMar, opt => opt.MapFrom(o => o.PresupuestoMarca))
                .ForMember(dest => dest.jefeMar, opt => opt.MapFrom(o => o.JefeMarca))
                .ForMember(dest => dest.getion, opt => opt.MapFrom(o => o.GestionadaRemotamenteMarca))
                .ForMember(dest => dest.icono, opt => opt.MapFrom(o => o.IconoMarca))
                .ForMember(dest => dest.tecnologia, opt => opt.MapFrom(o => o.TiposTecnologiaMarca))
                .ForMember(dest => dest.fRegistro, opt => opt.MapFrom(o => o.FechaRegistroMarca))
                .ForMember(dest => dest.fModificado, opt => opt.MapFrom(o => o.FechaModificacionMarca))
                .ForMember(dest => dest.SincronizarEcommerceMarca, opt => opt.MapFrom(o => o.SincronizarEcommerceMarca))
                .ForMember(dest => dest.EcommerceIdMarca, opt => opt.MapFrom(o => o.EcommerceIdMarca))
                .ForMember(dest => dest.usuMar, opt => opt.MapFrom(o => o.UsuariosMarca))
                .ForMember(dest => dest.usuModifica, opt => opt.MapFrom(o => o.UsuariosModificaMarca));

            CreateMap<Tiposproducto, TiposProductoDto>()
                 .ForMember(dest => dest.idTipos, opt => opt.MapFrom(o => o.CodigoTipoProducto))
                 .ForMember(dest => dest.desTipos, opt => opt.MapFrom(o => o.DescripcionTipoProducto))
                 .ForMember(dest => dest.presentacion, opt => opt.MapFrom(o => o.PresentaciónTipoProducto))
                 .ForMember(dest => dest.usuTipos, opt => opt.MapFrom(o => o.UsuariosTipoProductos));

            CreateMap<Producto, GetItems>()
                             .ForMember(dest => dest.id, opt => opt.MapFrom(o => o.CodigoProducto))
                             .ForMember(dest => dest.idVenta, opt => opt.MapFrom(o => o.CodigoVentaProducto))
                             .ForMember(dest => dest.idCompra, opt => opt.MapFrom(o => o.CodigoCompraProducto))
                             .ForMember(dest => dest.idBarra, opt => opt.MapFrom(o => o.CodigoBarraProducto))
                             .ForMember(dest => dest.idCatalogo, opt => opt.MapFrom(o => o.CodigoCatalogoProducto))
                             .ForMember(dest => dest.idmultiempresa, opt => opt.MapFrom(o => o.Idmultiempresas))
                             .ForMember(dest => dest.descripcion, opt => opt.MapFrom(o => o.DescripcionProducto))
                              .ForMember(dest => dest.descAd, opt => opt.MapFrom(o => o.DescripcionAdicionalProducto))
                              .ForMember(dest => dest.descCorta, opt => opt.MapFrom(o => o.DescripcionCortaProducto))
                              .ForMember(dest => dest.unidad, opt => opt.MapFrom(o => o.UnidadesProducto))
                              .ForMember(dest => dest.linea, opt => opt.MapFrom(o => o.LineasProducto))
                              .ForMember(dest => dest.categoria, opt => opt.MapFrom(o => o.CategoriasProducto))
                              .ForMember(dest => dest.grupo, opt => opt.MapFrom(o => o.GruposProducto))
                              .ForMember(dest => dest.marca, opt => opt.MapFrom(o => o.MarcasProducto))
                              .ForMember(dest => dest.color, opt => opt.MapFrom(o => o.ColoresProducto))
                              .ForMember(dest => dest.cuentasCompra, opt => opt.MapFrom(o => o.CuentasContabilidadCompraProducto))
                              .ForMember(dest => dest.cuentasVenta, opt => opt.MapFrom(o => o.CuentasContabilidadVentaProducto))
                              .ForMember(dest => dest.cuentasCosto, opt => opt.MapFrom(o => o.CuentasContabilidadCostoProducto))
                              .ForMember(dest => dest.cuentasDevolu, opt => opt.MapFrom(o => o.CuentasContabilidadDevolucionProducto))
                              .ForMember(dest => dest.CuentasContabilidadCuponProducto, opt => opt.MapFrom(o => o.CuentasContabilidadCuponProducto))
                              .ForMember(dest => dest.CuentasContabilidadDescuentoProducto, opt => opt.MapFrom(o => o.CuentasContabilidadDescuentoProducto))
                              .ForMember(dest => dest.cuentasActivo, opt => opt.MapFrom(o => o.CuentasContabilidadActivoProducto))
                              .ForMember(dest => dest.arancel, opt => opt.MapFrom(o => o.ArancelesProducto))
                              .ForMember(dest => dest.servicio, opt => opt.MapFrom(o => o.ServicioProducto))
                              .ForMember(dest => dest.pagaIva, opt => opt.MapFrom(o => o.PagaIvaProducto))
                              .ForMember(dest => dest.pagaIce, opt => opt.MapFrom(o => o.PagaIceProducto))
                              .ForMember(dest => dest.receta, opt => opt.MapFrom(o => o.RecetaProducto))
                              .ForMember(dest => dest.venta, opt => opt.MapFrom(o => o.VentaProducto))
                              .ForMember(dest => dest.activo, opt => opt.MapFrom(o => o.ActivoProducto))
                              .ForMember(dest => dest.serie, opt => opt.MapFrom(o => o.SerieLoteProducto))
                              .ForMember(dest => dest.lote, opt => opt.MapFrom(o => o.LoteProducto))
                              .ForMember(dest => dest.unidadCaja, opt => opt.MapFrom(o => o.UnidadesCajaProducto))
                              .ForMember(dest => dest.peso, opt => opt.MapFrom(o => o.PesoProducto))
                              .ForMember(dest => dest.alto, opt => opt.MapFrom(o => o.AltoProducto))
                              .ForMember(dest => dest.ancho, opt => opt.MapFrom(o => o.AnchoProducto))
                              .ForMember(dest => dest.profondidad, opt => opt.MapFrom(o => o.ProfundidadProducto))
                              .ForMember(dest => dest.precioFof, opt => opt.MapFrom(o => o.PrecioFofproducto))
                              .ForMember(dest => dest.materiaPrima, opt => opt.MapFrom(o => o.MateriaPrimaProducto))
                              .ForMember(dest => dest.ctrlPeso, opt => opt.MapFrom(o => o.ControlarPesoProducto))
                              .ForMember(dest => dest.repuesto, opt => opt.MapFrom(o => o.RepuestoProducto))
                              .ForMember(dest => dest.sustituto, opt => opt.MapFrom(o => o.SustitutoProducto))
                              .ForMember(dest => dest.accesorio, opt => opt.MapFrom(o => o.AccesorioProducto))
                              .ForMember(dest => dest.favorito, opt => opt.MapFrom(o => o.FavoritoProducto))
                              .ForMember(dest => dest.promo, opt => opt.MapFrom(o => o.PromocionProducto))
                              .ForMember(dest => dest.percha, opt => opt.MapFrom(o => o.PerchaProducto))
                              .ForMember(dest => dest.cultivo, opt => opt.MapFrom(o => o.CultivoProucto))
                              .ForMember(dest => dest.ctrl, opt => opt.MapFrom(o => o.ControlesProducto))
                              .ForMember(dest => dest.dosis, opt => opt.MapFrom(o => o.DosisProducto))
                              .ForMember(dest => dest.frecuencia, opt => opt.MapFrom(o => o.FrecuenciasProducto))
                              .ForMember(dest => dest.combo, opt => opt.MapFrom(o => o.ComboProducto))
                              .ForMember(dest => dest.descuentoCom, opt => opt.MapFrom(o => o.DescuentoComboProducto))
                              .ForMember(dest => dest.facturaCombo, opt => opt.MapFrom(o => o.FacturaComboProducto))
                              .ForMember(dest => dest.lista, opt => opt.MapFrom(o => o.ListasPrecioProducto))
                              .ForMember(dest => dest.facDecimal, opt => opt.MapFrom(o => o.FacturarDecimalesProducto))
                              .ForMember(dest => dest.selecc, opt => opt.MapFrom(o => o.SeleccionarPorcionesProducto))
                              .ForMember(dest => dest.observa, opt => opt.MapFrom(o => o.ObservacionProducto))
                              .ForMember(dest => dest.general, opt => opt.MapFrom(o => o.DatosGeneralesProducto))
                              .ForMember(dest => dest.ventaja, opt => opt.MapFrom(o => o.VentajasProducto))
                              .ForMember(dest => dest.desventaja, opt => opt.MapFrom(o => o.DesventajasProducto))
                              .ForMember(dest => dest.adicional, opt => opt.MapFrom(o => o.DatoAdicionalProducto))
                              .ForMember(dest => dest.tipos, opt => opt.MapFrom(o => o.ProductosTipoProducto))
                              .ForMember(dest => dest.proveedor, opt => opt.MapFrom(o => o.ProveedoresProducto))
                              .ForMember(dest => dest.precioProvee, opt => opt.MapFrom(o => o.PrecioProveedorLocalProducto))
                              .ForMember(dest => dest.variacion, opt => opt.MapFrom(o => o.VariacionCostoProduccionProducto))
                              .ForMember(dest => dest.metraje, opt => opt.MapFrom(o => o.MetrajeProducto))
                              .ForMember(dest => dest.porBoni, opt => opt.MapFrom(o => o.PorcentajeBonificacionProducto))
                              .ForMember(dest => dest.porDescuento, opt => opt.MapFrom(o => o.PorcentajeDescuentoProducto))
                              .ForMember(dest => dest.cantSumar, opt => opt.MapFrom(o => o.CantidadSumaBonificacionProducto))
                              .ForMember(dest => dest.filasSum, opt => opt.MapFrom(o => o.SumarNumeroFilasBonificacionProducto))
                              .ForMember(dest => dest.recargo, opt => opt.MapFrom(o => o.RecargoProducto))
                              .ForMember(dest => dest.califi, opt => opt.MapFrom(o => o.CalificacionProducto))
                              .ForMember(dest => dest.ctrlFuffer, opt => opt.MapFrom(o => o.ControlarBufferProducto))
                              .ForMember(dest => dest.tipoIce, opt => opt.MapFrom(o => o.CodigoTipoPorcentajeIce))
                              .ForMember(dest => dest.plan, opt => opt.MapFrom(o => o.PlanAnchoBanda))
                              .ForMember(dest => dest.CompresionServicio, opt => opt.MapFrom(o => o.CompresionServicio))
                              .ForMember(dest => dest.veriPlazo, opt => opt.MapFrom(o => o.VerificarPlazoLineasProducto))
                              .ForMember(dest => dest.motorChasis, opt => opt.MapFrom(o => o.IngresaMotorChasisProducto))
                              .ForMember(dest => dest.catServicio, opt => opt.MapFrom(o => o.CategoriasServicioTecnicoProducto))
                              .ForMember(dest => dest.tiempoServicio, opt => opt.MapFrom(o => o.TiempomedioServicioTecnicoProducto))
                              .ForMember(dest => dest.cantLitro, opt => opt.MapFrom(o => o.CantidadLitrosProducto))
                              .ForMember(dest => dest.gradoAlcohol, opt => opt.MapFrom(o => o.GradoAlcoholicoProducto))
                              .ForMember(dest => dest.valorPorLitro, opt => opt.MapFrom(o => o.ValorXlitroAlcoholProducto))
                              .ForMember(dest => dest.valorIce, opt => opt.MapFrom(o => o.ValorIcexItemProducto))
                              .ForMember(dest => dest.especial, opt => opt.MapFrom(o => o.CategoriasEspecialesProducto))
                              .ForMember(dest => dest.generaOrden, opt => opt.MapFrom(o => o.GeneraOrdenServicioTecnicoProducto))
                              .ForMember(dest => dest.sincroApp, opt => opt.MapFrom(o => o.SincronizarAppProducto))
                              .ForMember(dest => dest.sincroWeb, opt => opt.MapFrom(o => o.SincronizarWebProducto))
                              .ForMember(dest => dest.tipoExtra, opt => opt.MapFrom(o => o.TipoExtrasProducto))
                              .ForMember(dest => dest.descuento, opt => opt.MapFrom(o => o.DescuentoProducto))
                              .ForMember(dest => dest.visuaDesc, opt => opt.MapFrom(o => o.VisualizarDescuentoProducto))
                              .ForMember(dest => dest.esRecargas, opt => opt.MapFrom(o => o.EsServicioRecargasProducto))
                              .ForMember(dest => dest.EcommerceIdProducto, opt => opt.MapFrom(o => o.EcommerceIdProducto))
                              .ForMember(dest => dest.LineasEcommerceProducto, opt => opt.MapFrom(o => o.LineasEcommerceProducto))
                              .ForMember(dest => dest.CategoriasEcommerceProducto, opt => opt.MapFrom(o => o.CategoriasEcommerceProducto))
                              .ForMember(dest => dest.GruposEcommerceProducto, opt => opt.MapFrom(o => o.GruposEcommerceProducto))
                              .ForMember(dest => dest.MigarEcommerceProducto, opt => opt.MapFrom(o => o.MigarEcommerceProducto))
                              .ForMember(dest => dest.GruposCaracteristicasProducto, opt => opt.MapFrom(o => o.GruposCaracteristicasProducto))
                              .ForMember(dest => dest.DeshabilitadoProducto, opt => opt.MapFrom(o => o.DeshabilitadoProducto))
                              .ForMember(dest => dest.DeclaraArcsaProducto, opt => opt.MapFrom(o => o.DeclaraArcsaProducto))
                              .ForMember(dest => dest.NumeroRegistroSanitarioProducto, opt => opt.MapFrom(o => o.NumeroRegistroSanitarioProducto))
                              .ForMember(dest => dest.NombreComercialProducto, opt => opt.MapFrom(o => o.NombreComercialProducto))
                              .ForMember(dest => dest.CondicionesAlmacenamientoArcsaProducto, opt => opt.MapFrom(o => o.CondicionesAlmacenamientoArcsaProducto))
                              .ForMember(dest => dest.Anio, opt => opt.MapFrom(o => o.Anio))
                              .ForMember(dest => dest.Tonelaje, opt => opt.MapFrom(o => o.Tonelaje))
                              .ForMember(dest => dest.PaisOrigen, opt => opt.MapFrom(o => o.PaisOrigen))
                              .ForMember(dest => dest.Combustible, opt => opt.MapFrom(o => o.Combustible))
                              .ForMember(dest => dest.Cilindraje, opt => opt.MapFrom(o => o.Cilindraje))
                              .ForMember(dest => dest.Capacidad, opt => opt.MapFrom(o => o.Capacidad))
                              .ForMember(dest => dest.NumeroEjes, opt => opt.MapFrom(o => o.NumeroEjes))
                              .ForMember(dest => dest.NumeroRuedas, opt => opt.MapFrom(o => o.NumeroRuedas))
                              .ForMember(dest => dest.EmpresaProductos, opt => opt.MapFrom(o => o.Empresasproductos.FirstOrDefault()))
                              .ForMember(dest => dest.LineasItem, opt => opt.MapFrom(o => o.LineasProductoNavigation))
                              .ForMember(dest => dest.CategoriaItem, opt => opt.MapFrom(o => o.CategoriasProductoNavigation))
                              .ForMember(dest => dest.GrupoItem, opt => opt.MapFrom(o => o.GruposProductoNavigation))
                              .ForMember(dest => dest.MarcaItem, opt => opt.MapFrom(o => o.MarcasProductoNavigation))
                              .ForMember(dest => dest.TiposItem, opt => opt.MapFrom(o => o.TiposProductoNavigation))
                              ;
        }
    }
}
